from jazzhr_tap import run_jazz_tap

route = "questionnaire_answers"
schema = {'properties': {
    'job_id': {'type': ["string", "null"]},
    'applicant_id': {'type': 'string'},
    'questionnaire_id': {'type': 'string'},
    'questionnaire_code': {'type': 'string'},
    'answer_value_01': {'type': ["string", "null"]},
    'answer_correct_01': {'type': ["string", "null"]},
    'answer_value_02': {'type': ["string", "null"]},
    'answer_correct_02': {'type': ["string", "null"]},
    'answer_value_03': {'type': ["string", "null"]},
    'answer_correct_03': {'type': ["string", "null"]},
    'answer_value_04':{'type': ["string", "null"]},
    'answer_correct_04': {'type': ["string", "null"]},
    'answer_value_05': {'type': ["string", "null"]},
    'answer_correct_05': {'type': ["string", "null"]},
    'answer_value_06': {'type': ["string", "null"]},
    'answer_correct_06': {'type': ["string", "null"]},
    'answer_value_07': {'type': ["string", "null"]},
    'answer_correct_07': {'type': ["string", "null"]},
    'answer_value_08': {'type': ["string", "null"]},
    'answer_correct_08': {'type': ["string", "null"]},
    'answer_value_09': {'type': ["string", "null"]},
    'answer_correct_09': {'type': ["string", "null"]},
    'answer_value_10': {'type': ["string", "null"]},
    'answer_correct_10': {'type': ["string", "null"]},
    'answer_value_11': {'type': ["string", "null"]},
    'answer_correct_11': {'type': ["string", "null"]},
    'answer_value_12': {'type': ["string", "null"]},
    'answer_correct_12': {'type': ["string", "null"]},
    'answer_value_13': {'type': ["string", "null"]},
    'answer_correct_13': {'type': ["string", "null"]},
    'answer_value_14': {'type': ["string", "null"]},
    'answer_correct_14': {'type': ["string", "null"]},
    'answer_value_15': {'type': ["string", "null"]},
    'answer_correct_15': {'type': ["string", "null"]},
    'answer_value_16': {'type': ["string", "null"]},
    'answer_correct_16': {'type': ["string", "null"]},
    'answer_value_17': {'type': ["string", "null"]},
    'answer_correct_17': {'type': ["string", "null"]},
    'answer_value_18': {'type': ["string", "null"]},
    'answer_correct_18': {'type': ["string", "null"]},
    'answer_value_19': {'type': ["string", "null"]},
    'answer_correct_19': {'type': ["string", "null"]},
    'answer_value_20': {'type': ["string", "null"]},
    'answer_correct_20': {'type': ["string", "null"]},
    'date_taken': { "type": "string", "format": "date"},
    'time_taken': { "type": "string", "format": "time"}
    },
    "primary_key": "questionnaire_code",
     "required":[
               "job_id",
               "applicant_id",
               "questionnaire_id",
               "questionnaire_code",
               "date_taken",
               "time_taken",
               "answer_value_01",
               "answer_correct_01",
               "answer_value_02",
               "answer_correct_02",
               "answer_value_03",
               "answer_correct_03",
               "answer_value_04",
               "answer_correct_04",
               "answer_value_05",
               "answer_correct_05",
               "answer_value_06",
               "answer_correct_06",
               "answer_value_07",
               "answer_correct_07",
               "answer_value_08",
               "answer_correct_08",
               "answer_value_09",
               "answer_correct_09",
               "answer_value_10",
               "answer_correct_10",
               "answer_value_11",
               "answer_correct_11",
               "answer_value_12",
               "answer_correct_12",
               "answer_value_13",
               "answer_correct_13",
               "answer_value_14",
               "answer_correct_14",
               "answer_value_15",
               "answer_correct_15",
               "answer_value_16",
               "answer_correct_16",
               "answer_value_17",
               "answer_correct_17",
               "answer_value_18",
               "answer_correct_18",
               "answer_value_19",
               "answer_correct_19",
               "answer_value_20",
               "answer_correct_20",
            ]
  }
stream = "jazzhr_questionnaire_answers"
def read_record(item):
  return {
    "job_id": item['job_id'], 
    'applicant_id': item["applicant_id"],
    'questionnaire_id': item["questionnaire_id"],
    'questionnaire_code': item["questionnaire_code"],
    'date_taken': item["date_taken"],
    'time_taken': item["time_taken"],
    'answer_value_01': item.get("answer_correct_01",""),
    'answer_correct_01': item.get("answer_correct_01",""),
    'answer_value_02': item.get("answer_correct_02",""),
    'answer_correct_02': item.get("answer_correct_02",""),
    'answer_value_03': item.get("answer_correct_03",""),
    'answer_correct_03': item.get("answer_correct_03",""),
    'answer_value_04': item.get("answer_correct_04",""),
    'answer_correct_04': item.get("answer_correct_04",""),
    'answer_value_05': item.get("answer_correct_05",""),
    'answer_correct_05': item.get("answer_correct_05",""),
    'answer_value_06': item.get("answer_value_06",""),
    'answer_correct_06': item.get("answer_correct_06",""),
    'answer_value_07': item.get("answer_value_07",""),
    'answer_correct_07': item.get("answer_correct_07",""),
    'answer_value_08': item.get("answer_value_08",""),
    'answer_correct_08': item.get("answer_correct_08",""),
    'answer_value_09': item.get("answer_value_09",""),
    'answer_correct_09': item.get("answer_correct_09",""),
    'answer_value_10': item.get("answer_value_10",""),
    'answer_correct_10': item.get("answer_correct_10",""),
    'answer_value_11': item.get("answer_value_11",""),
    'answer_correct_11': item.get("answer_correct_11",""),
    'answer_value_12': item.get("answer_value_12",""),
    'answer_correct_12': item.get("answer_correct_12",""),
    'answer_value_13': item.get("answer_value_13",""),
    'answer_correct_13': item.get("answer_correct_13",""),
    'answer_value_14': item.get("answer_value_14",""),
    'answer_correct_14': item.get("answer_correct_14",""),
    'answer_value_15': item.get("answer_value_15",""),
    'answer_correct_15': item.get("answer_correct_15",""),
    'answer_value_16': item.get("answer_value_16",""),
    'answer_correct_16': item.get("answer_correct_16",""),
    'answer_value_17': item.get("answer_value_17",""),
    'answer_correct_17': item.get("answer_correct_17",""),
    'answer_value_18': item.get("answer_value_18",""),
    'answer_correct_18': item.get("answer_correct_18",""),
    'answer_value_19': item.get("answer_value_19",""),
    'answer_correct_19': item.get("answer_correct_19",""),
    'answer_value_20': item.get("answer_value_20",""),
    'answer_correct_20': item.get("answer_correct_20","")
    }
run_jazz_tap(route, schema, stream, read_record)